import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Nav, Search, Settings } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + ` bg-[#F7F8FA]`}>
        <div className="flex h-screen overflow-hidden">
          <div className="hidden xl:block ml-[40px] mt-[40px]">
            <Nav />
          </div>
          {/*============= for responsive=========== */}
          <div className="fixed xl:hidden bottom-0 w-screen bg-white rounded-tl-[45px] rounded-tr-[45px] py-5 shadow-2xl shadow-black">
            <Nav />
          </div>
          {/*============= for responsive=========== */}
          <div className="flex-1 xl:mt-[44px]">
            <div className="px-[20px] xl:px-[40px] bg-white xl:bg-inherit">
              <Search />
            </div>
            <div className="mx-[30px]">{children}</div>
          </div>
          <div className="hidden 2xl:block w-[330px] mt-[54px] mr-[40px]">
            <Settings />
          </div>
        </div>
      </body>
    </html>
  );
}
